run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - revive
    - ineffassign
    - errcheck
    - typecheck
    - structcheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-issues-per-report: 0

linters-settings:
  gofmt:
    simplify: true
  revive:
    ignore-generated-header: true
    severity: warning
